import Cookie from "js-cookie";
export const optionsPaymentMethod = [
  { value: "Cash", label: "Cash" },
  { value: "Referral", label: "Referral" },
  { value: "EFTinSCB", label: "EFT In SCB" },
  { value: "EFTinHMB", label: "EFT In HMB" },
  { value: "EFTinHBL", label: "EFT In HBL" },
  { value: "UnitedBank", label: "United Bank" },
  { value: "MeezanBank", label: "Meezan Bank" },
  { value: "SecurityChequeMeezan", label: "Security Cheque Meezan" },
  { value: "SilkBank", label: "Silk Bank" },
  { value: "BankAlfalah", label: "Bank Alfalah" },
  { value: "FaisalBankPayment", label: "Faisal Bank Payment" },
  { value: "NIBBankPayment", label: "NIB Bank Payment" },
  { value: "ChequeDisowned", label: "Cheque Disowned" },
  { value: "CreditCard", label: "Credit Card" },
  { value: "SecurityCheque", label: "Security Cheque" },
  {
    value: "InterconnectAdjustment",
    label: "Interconnect Expense Payable",
  },
  { value: "WHTonCustomerServices", label: "WHT On Customer Services" },
  { value: "Sales Tax", label: "Sales Tax" },
  { value: "Customer Refund Cheque", label: "Customer Refund Cheque" },
  { value: "Customer Refund Cash", label: "Customer Refund Cash" },
  { value: "OneLink Payment", label: "OneLink Payment" },
  { value: "JazzCash Payment", label: "JazzCash Payment" },
  { value: "Easy Paisa Payment", label: "EasyPaisa Payment" },
  { value: "Online Etisalat", label: "Online Etisalat Payment" },
  { value: "DIB Payment", label: "DIB Payment" },
  { value: "ALFALAH Payment", label: "Alfalah Payment" },
  { value: "TCSMode", label: "TCS Mode" },
  { value: "MCB", label: "MCB" },
  { value: "HMB", label: "HMB" },
  { value: "Askari Payment", label: "Askari Payment" },
  { value: "Askari Bank Collection", label: "Askari Bank Collection" },
  { value: "NBP Collection", label: "NBP Collection" },
  { value: "DIB Collection", label: "DIB Collection" },
  { value: "SAMBA Collection", label: "SAMBA Collection" },
];

//     { value: "Cash", label: "Cash" },
//     { value: "Referral", label: "Referral" },
//     { value: "EFT_IN_SCB", label: "EFT In SCB" },
//     { value: "EFT_IN_HMB", label: "EFT In HMB" },
//     { value: "EFT_IN_HBL", label: "EFT In HBL" },
//     { value: "UNITED_BANK", label: "United Bank" },
//     { value: "MEEZAN_BANK", label: "Meezan Bank" },
//     { value: "SECURITY_CHEQUE_MEEZAN", label: "Security Cheque Meezan" },
//     { value: "SILK_BANK", label: "Silk Bank" },
//     { value: "BANK_ALFALAH", label: "Bank Alfalah" },
//     { value: "FAISAL_BANK_PAYMENT", label: "Faisal Bank Payment" },
//     { value: "NIB_BANK_PAYMENT", label: "NIB Bank Payment" },
//     { value: "CHEQUE_DISOWNED", label: "Cheque Disowned" },
//     { value: "CREDIT_CARD", label: "Credit Card" },
//     { value: "SECURITY_CHEQUE", label: "Security Cheque" },
//     {
//       value: "INTERCONNECT_EXPENSE_PAYABLE",
//       label: "Interconnect Expense Payable",
//     },
//     { value: "WHT_ON_CUSTOMER_SERVICES", label: "WHT On Customer Services" },
//     { value: "SALETAX", label: "Sales Tax" },
//     { value: "CUSTOMER_REFUND_CHEQUE", label: "Customer Refund Cheque" },
//     { value: "CUSTOMER_REFUND_CASH", label: "Customer Refund Cash" },
//     { value: "ONELINK_PAYMENT", label: "OneLink Payment" },
//     { value: "JAZZCASH_PAYMENT", label: "JazzCash Payment" },
//     { value: "EASYPAISA_PAYMENT", label: "EasyPaisa Payment" },
//     { value: "ONLINE_ETISALAT_PAYMENT", label: "Online Etisalat Payment" },
//     { value: "DIB_PAYMENT", label: "DIB Payment" },
//     { value: "ALFALAH_PAYMENT", label: "Alfalah Payment" },
//     { value: "TCS_MODE", label: "TCS Mode" },
//     { value: "MCB", label: "MCB" },
//     { value: "HMB", label: "HMB" },
//     { value: "ASKARI_PAYMENT", label: "Askari Payment" },
//     { value: "ASKARI_BANK_COLLECTION", label: "Askari Bank Collection" },
//     { value: "NBP_COLLECTION", label: "NBP Collection" },
//     { value: "DIB_COLLECTION", label: "DIB Collection" },
//     { value: "SAMBA_COLLECTION", label: "SAMBA Collection" },
//   ];

export const optionsBankAccount = [
  { value: "STANDARD_CHARTERED", label: "Standard Chartered" },
  { value: "ASKARI_BANK", label: "Askari Bank" },
  { value: "MEEZAN_BANK", label: "Meezan Bank" },
  { value: "BANK_ALFALAH", label: "Bank Alfalah" },
  { value: "ALLIED_BANK", label: "Allied Bank" },
  { value: "SILK_BANK", label: "Silk Bank" },
  { value: "BANK_AL_HABIB", label: "Bank Al Habib" },
  { value: "UNITED_BANK", label: "United Bank" },
  { value: "HABIB_METROPOLITAN_BANK", label: "Habib Metropolitan Bank" },
  { value: "MUSLIM_COMMERCIAL_BANK", label: "Muslim Commercial Bank" },
  { value: "NATIONAL_BANK", label: "National Bank" },
  { value: "BANK_ISLAMI_PAKISTAN", label: "Bank Islami Pakistan" },
  { value: "SUMMIT_BANK", label: "Summit Bank" },
  { value: "BANK_OF_PUNJAB", label: "Bank of Punjab" },
  { value: "NRSP_MICRO_FINANCE", label: "NRSP Micro Finance" },
  { value: "DUBAI_ISLAMIC_BANK", label: "Dubai Islamic Bank" },
  { value: "FINCA", label: "FINCA" },
  { value: "U_BANK", label: "U Bank" },
  { value: "FIRST_MICRO_FINANCE_BANK", label: "First Micro Finance Bank" },
  { value: "FIRST_WOMEN_BANK", label: "First Women Bank" },
  { value: "STATE_BANK", label: "State Bank" },
  { value: "CITI_BANK", label: "Citi Bank" },
  { value: "SAMBA_BANK", label: "Samba Bank" },
  { value: "SONERI_BANK", label: "Soneri Bank" },
  {
    value: "ZARAI_TARAQIATI_BANK_LIMITED",
    label: "Zarai Taraqiati Bank Limited",
  },
  { value: "JS_BANK", label: "JS Bank" },
  { value: "AL_BARAKA_BANK", label: "Al Baraka Bank" },
  { value: "SINDH_BANK", label: "Sindh Bank" },
  { value: "THE_BANK_OF_KHYBER", label: "The Bank of Khyber" },
  { value: "FAYSAL_BANK", label: "Faysal Bank" },
  {
    value: "INDUSTRIAL_DEVELOPMENT_BANK",
    label: "Industrial Development Bank",
  },
  {
    value: "INDUSTRIAL_AND_COMMERCIAL_BANK_OF_CHINA",
    label: "Industrial and Commercial Bank of China",
  },
  { value: "GOP", label: "GOP" },
  { value: "HBL", label: "HBL" },
  { value: "KASB_BANK", label: "KASB Bank" },
  { value: "SME_BANK", label: "SME Bank" },
  { value: "APNA_BANK", label: "Apna Bank" },
  { value: "MIB_BANK", label: "MIB Bank" },
  { value: "DEUTSCHE_BANK", label: "Deutsche" },

  {
    value: "MOBILINK_MICRO_FINANCE_BANK",
    label: " Mobilink Micro Finance Bank",
  },
  {
    value: "KHUSHHALI_MICRO_FINANCE_BANK",
    label: "Khushhali Micro Finance Bank",
  },
  { value: "TELENOR_MICROFINANCE_BANK", label: "Telenor Microfinance Bank" },
  { value: "NATIONAL_SAVING_CENTRE", label: "National Saving Centre" },
];

export const optionsSelect = [
  { value: "", label: "Please Select...", disabled: true },
  { value: "3", label: "3%" },
  { value: "8", label: "8%" },
  { value: "10", label: "10%" },
];

export const optionsCity = [
  // { value: "", label: "Please Select..." },
  { value: "ISLAMABAD", label: "Islamabad" },
  { value: "RAWALPINDI", label: "Rawalpindi" },
  { value: "FAISALABAD", label: "Faisalabad" },
  { value: "PESHAWAR", label: "Peshawar" },
];

export const optionsMerchant = [
  { value: "MCB", label: "MCB" },
  { value: "BAL", label: "BAL" },
];

export const optionsTax1 = [
  { value: "0", label: "0%" },
  { value: "3", label: "3%" },
  { value: "8", label: "8%" },
  { value: "10", label: "10%" },
];
export const optionsTax2 = [
  { value: "20", label: "20%" },
  { value: "100", label: "100%" },
];
export const optionsTaxPercentage = [
  { value: "20", label: "20%" },
  { value: "100", label: "100%" },
];
export const merchantOptions = [
  { value: "", label: "Please Select..." },
  { value: "MCB", label: "MCB" },
  { value: "BAL", label: "BAL" },
];
export const forOptions = [
  { value: "", label: "Select For" },
  { value: "ONT", label: "ONT" },
  { value: "HDBOX", label: "HD BOX" },
  { value: "SETTOPBOX", label: "SET TOP BOX" },
  { value: "EXTENDEDWARRANTY", label: "EXTENDED WARRANTY" },
  { value: "ATA", label: "ATA" },
  { value: "REPLACEDONT", label: "REPLACED ONT" },
  { value: "MULTIPLEHARDWARES", label: "MULTIPLE HARDWARES" },
  { value: "OTHERS", label: "OTHERS" },
];
export const statusOptions = [
  { value: "", label: "Select Status" },
  { value: "INITIALCHEQUERECEIVED", label: "INITIAL CHEQUE RECEIVED" },
  { value: "DISPATCHEDONADDRESS", label: "DISPATCHED ON ADDRESS" },
  { value: "HANDED_OVERTOCUSTOMER", label: "HANDED OVER TO CUSTOMER" },
  { value: "PRESENTEDLOCKEDWORKING", label: "PRESENTED LOCKED WORKING" },
  {
    value: "USEDAGAINSTANOTHERHARDWARE",
    label: "USED AGAINST ANOTHER HARDWARE",
  },
  { value: "USEDAGAINSTANOTHERID", label: "USED AGAINST ANOTHER ID" },
  { value: "USED_AGAINST_PAYMENT", label: "USED AGAINST PAYMENT" },
];
