//Test
export const EDIT_FORM_CONSTANTS = {
  EDIT_NAP: "EDIT NAP",
  EDIT_SAFETY: "EDIT SAFETY",
  EDIT_CP: "EDIT CP",
  EDIT_DC: "EDIT DC",
  EDIT_FTTH: "EDIT FTTH",
  EDIT_SECONDARY_DJS: "EDIT SECONDARY DJS",
  EDIT_PRIMARY_DJS: "EDIT PRIMARY DJS",
  EDIT_ODF: "EDIT ODF",
  EDIT_ODFS: "EDIT ODFS",
  EDIT_MINI_DC: "EDIT MINI DC",
};
